#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "N2O4 <=> NO2 + NO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+12,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Exact match found for rate rule [RJJ]
    Euclidian distance = 0
    family: 1,4_Linear_birad_scission"""),
    longDesc = 
"""
Exact match found for rate rule [RJJ]
Euclidian distance = 0
family: 1,4_Linear_birad_scission
""",
)

entry(
    index = 1,
    label = "N2O4 => [O][N]OON=O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1e+10,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [NOS]
    Euclidian distance = 0
    family: 1,2-Birad_to_alkene"""),
    longDesc = 
"""
Estimated using an average for rate rule [NOS]
Euclidian distance = 0
family: 1,2-Birad_to_alkene
""",
)

entry(
    index = 2,
    label = "NO2 + NO2 <=> [O][N]OON=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(260000,'m^3/(mol*s)'), n=0, Ea=(241.608,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R_R;OJ-OneDe] for rate rule [Od_N3d;OJ-NO]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond
    Ea raised from 241.3 to 241.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [R_R;OJ-OneDe] for rate rule [Od_N3d;OJ-NO]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
Ea raised from 241.3 to 241.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 3,
    label = "[N]=O + [O]O[N][O] <=> N2O4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(12314.5,'m^3/(mol*s)'), n=0.968108, Ea=(-2.00346,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O_rad/NonDe;Birad] for rate rule [O_rad/NonDe;N_birad/O]
    Euclidian distance = 2.0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Estimated using template [O_rad/NonDe;Birad] for rate rule [O_rad/NonDe;N_birad/O]
Euclidian distance = 2.0
family: Birad_R_Recombination
""",
)

entry(
    index = 4,
    label = "N2O4 + N2O4 <=> [O][N]OO[N]OO[N]OO[N][O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(5.26e+08,'m^3/(mol*s)'), n=-1.1, Ea=(3.88764,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_N-2NO->O',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_N-2NO->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_N-2NO->O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_N-2NO->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_N-2NO->O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 5,
    label = "[O][N]OO[N]OO[N]OO[N][O] <=> [O][N]OON=O + [O][N]OON=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+12,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Exact match found for rate rule [RJJ]
    Euclidian distance = 0
    family: 1,4_Linear_birad_scission"""),
    longDesc = 
"""
Exact match found for rate rule [RJJ]
Euclidian distance = 0
family: 1,4_Linear_birad_scission
""",
)

entry(
    index = 6,
    label = "O2 + [N]=O <=> [O]O[N][O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.53658e+08,'m^3/(mol*s)'), n=-0.375, Ea=(5.83765,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;N_R_birad] for rate rule [Y_rad;N_birad/O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Birad_R_Recombination
    Ea raised from 2.6 to 5.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Y_rad;N_R_birad] for rate rule [Y_rad;N_birad/O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Birad_R_Recombination
Ea raised from 2.6 to 5.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 7,
    label = "O + O <=> O2",
    degeneracy = 1.0,
    kinetics = ThirdBody(arrheniusLow=Arrhenius(A=(6.165e+15,'cm^6/(mol^2*s)'), n=-0.5, Ea=(0,'cal/mol'), T0=(1,'K')), efficiencies={'O': 12, 'O=C=O': 3.8, '[Ar]': 0, '[C-]#[O+]': 1.9, '[H][H]': 2.5, '[He]': 0}),
    longDesc = 
"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 8,
    label = "O + NO2 <=> [O]O[N][O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(23.3993,'m^3/(mol*s)'), n=2.021, Ea=(44.3349,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Od_R;YJ] for rate rule [Od_N3d;O_atom_triplet]
    Euclidian distance = 2.8284271247461903
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond
    Ea raised from 42.6 to 44.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Od_R;YJ] for rate rule [Od_N3d;O_atom_triplet]
Euclidian distance = 2.8284271247461903
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
Ea raised from 42.6 to 44.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 9,
    label = "[N]=O + ONOOJ <=> [O][N]OON=O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(12314.5,'m^3/(mol*s)'), n=0.968108, Ea=(-2.00346,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O_rad/NonDe;Birad] for rate rule [O_rad/NonDe;N_birad/O]
    Euclidian distance = 2.0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Estimated using template [O_rad/NonDe;Birad] for rate rule [O_rad/NonDe;N_birad/O]
Euclidian distance = 2.0
family: Birad_R_Recombination
""",
)

entry(
    index = 10,
    label = "[O]O[N][O] => ONOOJ",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1e+10,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [NOS]
    Euclidian distance = 0
    family: 1,2-Birad_to_alkene"""),
    longDesc = 
"""
Estimated using an average for rate rule [NOS]
Euclidian distance = 0
family: 1,2-Birad_to_alkene
""",
)

entry(
    index = 11,
    label = "O + NO2 <=> ONOOJ",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(24628.9,'m^3/(mol*s)'), n=0.968108, Ea=(-2.00346,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [O_sec_rad;O_birad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Estimated using an average for rate rule [O_sec_rad;O_birad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Birad_R_Recombination
""",
)

entry(
    index = 12,
    label = "[N]=O + ONOOJ <=> [O][N]OON=O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(12314.5,'m^3/(mol*s)'), n=0.968108, Ea=(-2.00346,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O_rad/NonDe;Birad] for rate rule [O_rad/NonDe;N_birad/O]
    Euclidian distance = 2.0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Estimated using template [O_rad/NonDe;Birad] for rate rule [O_rad/NonDe;N_birad/O]
Euclidian distance = 2.0
family: Birad_R_Recombination
""",
)

entry(
    index = 13,
    label = "NO2 + NO2 <=> ONOONO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(212954,'m^3/(mol*s)'), n=0.348287, Ea=(62.8313,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.0108230153501, var=2.70964383578, Tref=1000.0, N=19, correlation='Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R
        Total Standard Deviation in ln(k): 3.32718707999
    Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination
    Ea raised from 62.1 to 62.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R
    Total Standard Deviation in ln(k): 3.32718707999
Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
Ea raised from 62.1 to 62.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 14,
    label = "[O][N]OON=O => ONOONO",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1e+10,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [NOS]
    Euclidian distance = 0
    family: 1,2-Birad_to_alkene"""),
    longDesc = 
"""
Estimated using an average for rate rule [NOS]
Euclidian distance = 0
family: 1,2-Birad_to_alkene
""",
)

entry(
    index = 15,
    label = "NO2 + N2O4 <=> [O][N]OO[N]OON=O",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(488000,'m^3/(mol*s)'), n=0.2, Ea=(29.5503,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: R_Recombination
    Ea raised from 27.0 to 29.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: R_Recombination
Ea raised from 27.0 to 29.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 16,
    label = "NO2 + [O][N]OON=O <=> [O][N]OO[N]OON=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(260000,'m^3/(mol*s)'), n=0, Ea=(206.113,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R_R;OJ-OneDe] for rate rule [Od_N3d;OJ-NO]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond
    Ea raised from 203.6 to 206.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [R_R;OJ-OneDe] for rate rule [Od_N3d;OJ-NO]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
Ea raised from 203.6 to 206.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 17,
    label = "[O][N]OO[N]OO[N]OO[N][O] <=> NO2 + [O][N]OO[N]OON=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1e+13,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Exact match found for rate rule [RJJ]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: 1,4_Linear_birad_scission"""),
    longDesc = 
"""
Exact match found for rate rule [RJJ]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: 1,4_Linear_birad_scission
""",
)

entry(
    index = 18,
    label = "[O][N]OO[N]OON=O <=> NO2 + ONOONO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+12,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Exact match found for rate rule [RJJ]
    Euclidian distance = 0
    family: 1,4_Linear_birad_scission"""),
    longDesc = 
"""
Exact match found for rate rule [RJJ]
Euclidian distance = 0
family: 1,4_Linear_birad_scission
""",
)

entry(
    index = 19,
    label = "O + NO <=> NO2",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Troe(arrheniusHigh=Arrhenius(A=(1.3e+15,'cm^3/(mol*s)'), n=-0.75, Ea=(0,'cal/mol'), T0=(1,'K')), arrheniusLow=Arrhenius(A=(4.72e+24,'cm^6/(mol^2*s)'), n=-2.87, Ea=(1550,'cal/mol'), T0=(1,'K')), alpha=0.75, T3=(1000,'K'), T1=(100000,'K'), T2=(1e+30,'K'), efficiencies={}),
    longDesc = 
"""
Originally from reaction library: NOx2018
""",
)

entry(
    index = 20,
    label = "O + NO2 <=> O2 + NO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1e+14,'cm^3/(mol*s)'), n=-0.52, Ea=(0,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: NOx2018
""",
)

entry(
    index = 21,
    label = "NO2 + NO2 <=> O2 + NO + NO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.5e+12,'cm^3/(mol*s)'), n=0, Ea=(27599,'cal/mol'), T0=(1,'K')),
    longDesc = 
"""
Originally from reaction library: NOx2018
""",
)

entry(
    index = 22,
    label = "NO + [O]O[N][O] <=> [O][N]OON=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(122000,'m^3/(mol*s)'), n=0.2, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 23,
    label = "O2 + NO <=> ONOOJ",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(117000,'m^3/(mol*s)','*|/',-1), n=0, Ea=(51.7084,'kJ/mol','+|-',-0.001), T0=(1,'K'), Tmin=(473,'K'), Tmax=(703,'K'), Pmin=(1333,'Pa'), Pmax=(33600,'Pa'), comment="""Matched reaction 5 NO + O2 <=> NO3 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_N-3R!H-u0_Ext-1N-R]
    family: R_Recombination
    Ea raised from 13.4 to 51.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 5 NO + O2 <=> NO3 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_N-3R!H-u0_Ext-1N-R]
family: R_Recombination
Ea raised from 13.4 to 51.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 24,
    label = "NO + ONOOJ <=> ONOONO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(122000,'m^3/(mol*s)'), n=0.2, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_2NO->O]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 25,
    label = "[N]=O + N2O4 <=> [O][N]OO[N]O[N][O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.53658e+08,'m^3/(mol*s)'), n=-0.375, Ea=(2.56479,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;N_R_birad] for rate rule [Y_rad;N_birad/O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Birad_R_Recombination"""),
    longDesc = 
"""
Estimated using template [Y_rad;N_R_birad] for rate rule [Y_rad;N_birad/O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Birad_R_Recombination
""",
)

entry(
    index = 26,
    label = "[N]=O + [O][N]OON=O <=> [O][N]OO[N]O[N][O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(11.6997,'m^3/(mol*s)'), n=2.021, Ea=(75.019,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Od_R;YJ] for rate rule [Od_N3d;Y_1centerbirad]
    Euclidian distance = 2.23606797749979
    family: R_Addition_MultipleBond
    Ea raised from 70.3 to 75.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Od_R;YJ] for rate rule [Od_N3d;Y_1centerbirad]
Euclidian distance = 2.23606797749979
family: R_Addition_MultipleBond
Ea raised from 70.3 to 75.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 27,
    label = "[O][N]OO[N]OO[N]OO[N][O] <=> [O][N]OON1OON1OO[N][O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.62e+12,'s^-1'), n=-0.305, Ea=(8.28432,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [R4_SSS;Y_rad_out;Ypri_rad_out]
    Euclidian distance = 0
    family: Birad_recombination"""),
    longDesc = 
"""
Estimated using an average for rate rule [R4_SSS;Y_rad_out;Ypri_rad_out]
Euclidian distance = 0
family: Birad_recombination
""",
)

entry(
    index = 28,
    label = "N2O4 + [O][N]OON=O <=> [O][N]OO[N]OO[N]OON=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(5.26e+08,'m^3/(mol*s)'), n=-1.1, Ea=(3.88764,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_N-2NO->O',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_N-2NO->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_N-2NO->O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_N-2NO->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C_Ext-1N-R_N-2NO->O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 29,
    label = "[O][N]OO[N]OO[N]OO[N][O] => [O][N]OO[N]OO[N]OON=O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1e+10,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [NOS]
    Euclidian distance = 0
    family: 1,2-Birad_to_alkene"""),
    longDesc = 
"""
Estimated using an average for rate rule [NOS]
Euclidian distance = 0
family: 1,2-Birad_to_alkene
""",
)

entry(
    index = 30,
    label = "[O][N]OO[N]OO[N]OON=O <=> ONOONO + [O][N]OON=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+12,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Exact match found for rate rule [RJJ]
    Euclidian distance = 0
    family: 1,4_Linear_birad_scission"""),
    longDesc = 
"""
Exact match found for rate rule [RJJ]
Euclidian distance = 0
family: 1,4_Linear_birad_scission
""",
)

entry(
    index = 31,
    label = "NO2 + [O][N]OO[N]OON=O <=> [O][N]OO[N]OO[N]OON=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(260000,'m^3/(mol*s)'), n=0, Ea=(206.113,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R_R;OJ-OneDe] for rate rule [Od_N3d;OJ-NO]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond
    Ea raised from 203.6 to 206.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [R_R;OJ-OneDe] for rate rule [Od_N3d;OJ-NO]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
Ea raised from 203.6 to 206.1 kJ/mol to match endothermicity of reaction.
""",
)

